name: Module Descriptor Validation Report
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: |
        echo '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
              <modelVersion>4.0.0</modelVersion>
              <groupId>dummy</groupId>
              <artifactId>dummy</artifactId>
              <version>0.0.0</version>
              <pluginRepositories>
                <pluginRepository>
                  <id>folio-nexus</id>
                  <name>FOLIO Maven repository</name>
                  <url>https://repository.folio.org/repository/maven-folio</url>
                </pluginRepository>
              </pluginRepositories>
            </project>' > pom.xml
        modules='
          mod-agreements master/service/src/main/okapi/ModuleDescriptor-template.json
          mod-permissions
        '
        echo "$modules" | while read line; do
          set -- $line
          if [ -z "$1" ]; then
            continue
          fi
          path="${2:-master/descriptors/ModuleDescriptor-template.json}"
          wget "https://raw.githubusercontent.com/folio-org/$1/$path" -O /tmp/md
          echo "$1" >> $GITHUB_STEP_SUMMARY
          mvn -B org.folio:folio-module-descriptor-validator:1.0.0:validate -DmoduleDescriptorFile=/tmp/md \
            | sed -n '/^\[ERROR\] -> \[Help 1\]/q; /^\[ERROR\] /{s///; s/^Failed.*Module descriptor not valid: \[ {$/[ {/; p}' \
            >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
        done
