name: Module Descriptor Validation Report
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: |
        echo '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
              <modelVersion>4.0.0</modelVersion>
              <groupId>dummy</groupId>
              <artifactId>dummy</artifactId>
              <version>0.0.0</version>
              <pluginRepositories>
                <pluginRepository>
                  <id>folio-nexus</id>
                  <name>FOLIO Maven repository</name>
                  <url>https://repository.folio.org/repository/maven-folio</url>
                </pluginRepository>
              </pluginRepositories>
            </project>' > pom.xml
        modules='
          folio-custom-fields
          mod-agreements       master/service/src/main/okapi/ModuleDescriptor-template.json
          mod-audit
          mod-authtoken
          mod-batch-print
          mod-bulk-operations
          mod-calendar
          mod-camunda
          mod-circulation
          mod-circulation-item
          mod-circulation-storage
          mod-configuration
          mod-consortia
          mod-courses
          mod-copycat
          mod-data-export
          mod-data-export-spring
          mod-data-export-worker
          mod-data-import
          mod-dcb
          mod-di-converter-storage
          mod-ebsconet
          mod-entities-links
          mod-email
          mod-eusage-reports
          mod-erm-usage
          mod-erm-usage-harvester
          mod-event-config
          mod-feesfines
          mod-finance
          mod-finance-storage
          mod-fqm-manager
          mod-gobi
          mod-graphql               master/ModuleDescriptor.json
          mod-inn-reach
          mod-inventory
          mod-invoice
          mod-invoice-storage
          mod-inventory-storage
          mod-inventory-update
          mod-kb-ebsco-java
          mod-ldp
          mod-licenses              master/service/src/main/okapi/ModuleDescriptor-template.json
          mod-lists
          mod-login
          mod-login-saml
          mod-marc-migrations
          mod-ncip
          mod-notes
          mod-notify
          mod-oa                    master/service/src/main/okapi/ModuleDescriptor-template.json
          mod-oai-pmh
          mod-orders
          mod-orders-storage
          mod-organizations
          mod-organizations-storage
          mod-patron-blocks
          mod-patron 
          mod-permissions
          mod-pubsub
          mod-password-validator
          mod-quick-marc
          mod-requests-mediated
          mod-reading-room
          mod-record-specifications
          mod-remote-storage
          mod-rtac
          mod-search
          mod-sender
          mod-serials-management    master/service/src/main/okapi/ModuleDescriptor-template.json
          mod-service-interaction   master/service/src/main/okapi/ModuleDescriptor-template.json
          mod-settings
          mod-source-record-storage
          mod-source-record-manager
          mod-tags
          mod-template-engine
          mod-tlr
          mod-user-import
          mod-users-bl
          mod-users
          mod-workflow
        '
        echo "$modules" | while read line; do
          set -- $line
          if [ -z "$1" ]; then
            continue
          fi
          path="${2:-master/descriptors/ModuleDescriptor-template.json}"
          wget "https://raw.githubusercontent.com/folio-org/$1/$path" -O /tmp/md
          echo "## $1" >> $GITHUB_STEP_SUMMARY
          mvn -B org.folio:folio-module-descriptor-validator:1.0.0:validate -DmoduleDescriptorFile=/tmp/md \
            | sed -n '/^\[ERROR\] -> \[Help 1\]/q; /^\[ERROR\] /{s///; s/^Failed.*Module descriptor not valid: \[ {$/[ {/; p}' \
            >> $GITHUB_STEP_SUMMARY
        done
